import time, random
from locust import FastHttpUser, task, between

TODO_LSIT = [
    {"title": "Go to the gym - Day 1", "description": "Workout for 1 minutes"},
    {"title": "Go to the gym - Day 2", "description": "Workout for 2 minutes"},
    {"title": "Go to the gym - Day 3", "description": "Workout for 3 minutes"},
    {"title": "Go to the gym - Day 4", "description": "Workout for 4 minutes"},
    {"title": "Go to the gym - Day 5", "description": "Workout for 5 minutes"},
    {"title": "Go to the gym - Day 6", "description": "Workout for 6 minutes"},
    {"title": "Go to the gym - Day 7", "description": "Workout for 7 minutes"},
    {"title": "Go to the gym - Day 8", "description": "Workout for 8 minutes"},
    {"title": "Go to the gym - Day 9", "description": "Workout for 9 minutes"},
    {"title": "Go to the gym - Day 10", "description": "Workout for 10 minutes"},
    {"title": "Go to the gym - Day 11", "description": "Workout for 11 minutes"},
    {"title": "Go to the gym - Day 12", "description": "Workout for 12 minutes"},
    {"title": "Go to the gym - Day 13", "description": "Workout for 13 minutes"},
    {"title": "Go to the gym - Day 14", "description": "Workout for 14 minutes"},
    {"title": "Go to the gym - Day 15", "description": "Workout for 15 minutes"},
    {"title": "Go to the gym - Day 16", "description": "Workout for 16 minutes"},
    {"title": "Go to the gym - Day 17", "description": "Workout for 17 minutes"},
    {"title": "Go to the gym - Day 18", "description": "Workout for 18 minutes"},
    {"title": "Go to the gym - Day 19", "description": "Workout for 19 minutes"},
    {"title": "Go to the gym - Day 20", "description": "Workout for 20 minutes"},
    {"title": "Go to the gym - Day 21", "description": "Workout for 21 minutes"},
    {"title": "Go to the gym - Day 22", "description": "Workout for 22 minutes"},
    {"title": "Go to the gym - Day 23", "description": "Workout for 23 minutes"},
    {"title": "Go to the gym - Day 24", "description": "Workout for 24 minutes"},
    {"title": "Go to the gym - Day 25", "description": "Workout for 25 minutes"},
    {"title": "Go to the gym - Day 26", "description": "Workout for 26 minutes"},
    {"title": "Go to the gym - Day 27", "description": "Workout for 27 minutes"},
    {"title": "Go to the gym - Day 28", "description": "Workout for 28 minutes"},
    {"title": "Go to the gym - Day 29", "description": "Workout for 29 minutes"},
    {"title": "Go to the gym - Day 30", "description": "Workout for 30 minutes"},
    {"title": "Go to the gym - Day 31", "description": "Workout for 31 minutes"},
    {"title": "Go to the gym - Day 32", "description": "Workout for 32 minutes"},
    {"title": "Go to the gym - Day 33", "description": "Workout for 33 minutes"},
    {"title": "Go to the gym - Day 34", "description": "Workout for 34 minutes"},
    {"title": "Go to the gym - Day 35", "description": "Workout for 35 minutes"},
    {"title": "Go to the gym - Day 36", "description": "Workout for 36 minutes"},
    {"title": "Go to the gym - Day 37", "description": "Workout for 37 minutes"},
    {"title": "Go to the gym - Day 38", "description": "Workout for 38 minutes"},
    {"title": "Go to the gym - Day 39", "description": "Workout for 39 minutes"},
    {"title": "Go to the gym - Day 40", "description": "Workout for 40 minutes"},
    {"title": "Go to the gym - Day 41", "description": "Workout for 41 minutes"},
    {"title": "Go to the gym - Day 42", "description": "Workout for 42 minutes"},
    {"title": "Go to the gym - Day 43", "description": "Workout for 43 minutes"},
    {"title": "Go to the gym - Day 44", "description": "Workout for 44 minutes"},
    {"title": "Go to the gym - Day 45", "description": "Workout for 45 minutes"},
    {"title": "Go to the gym - Day 46", "description": "Workout for 46 minutes"},
    {"title": "Go to the gym - Day 47", "description": "Workout for 47 minutes"},
    {"title": "Go to the gym - Day 48", "description": "Workout for 48 minutes"},
    {"title": "Go to the gym - Day 49", "description": "Workout for 49 minutes"},
    {"title": "Go to the gym - Day 50", "description": "Workout for 50 minutes"},
    {"title": "Go to the gym - Day 51", "description": "Workout for 51 minutes"},
    {"title": "Go to the gym - Day 52", "description": "Workout for 52 minutes"},
    {"title": "Go to the gym - Day 53", "description": "Workout for 53 minutes"},
    {"title": "Go to the gym - Day 54", "description": "Workout for 54 minutes"},
    {"title": "Go to the gym - Day 55", "description": "Workout for 55 minutes"},
    {"title": "Go to the gym - Day 56", "description": "Workout for 56 minutes"},
    {"title": "Go to the gym - Day 57", "description": "Workout for 57 minutes"},
    {"title": "Go to the gym - Day 58", "description": "Workout for 58 minutes"},
    {"title": "Go to the gym - Day 59", "description": "Workout for 59 minutes"},
    {"title": "Go to the gym - Day 60", "description": "Workout for 60 minutes"},
    {"title": "Go to the gym - Day 61", "description": "Workout for 61 minutes"},
    {"title": "Go to the gym - Day 62", "description": "Workout for 62 minutes"},
    {"title": "Go to the gym - Day 63", "description": "Workout for 63 minutes"},
    {"title": "Go to the gym - Day 64", "description": "Workout for 64 minutes"},
    {"title": "Go to the gym - Day 65", "description": "Workout for 65 minutes"},
    {"title": "Go to the gym - Day 66", "description": "Workout for 66 minutes"},
    {"title": "Go to the gym - Day 67", "description": "Workout for 67 minutes"},
    {"title": "Go to the gym - Day 68", "description": "Workout for 68 minutes"},
    {"title": "Go to the gym - Day 69", "description": "Workout for 69 minutes"},
    {"title": "Go to the gym - Day 70", "description": "Workout for 70 minutes"},
    {"title": "Go to the gym - Day 71", "description": "Workout for 71 minutes"},
    {"title": "Go to the gym - Day 72", "description": "Workout for 72 minutes"},
    {"title": "Go to the gym - Day 73", "description": "Workout for 73 minutes"},
    {"title": "Go to the gym - Day 74", "description": "Workout for 74 minutes"},
    {"title": "Go to the gym - Day 75", "description": "Workout for 75 minutes"},
    {"title": "Go to the gym - Day 76", "description": "Workout for 76 minutes"},
    {"title": "Go to the gym - Day 77", "description": "Workout for 77 minutes"},
    {"title": "Go to the gym - Day 78", "description": "Workout for 78 minutes"},
    {"title": "Go to the gym - Day 79", "description": "Workout for 79 minutes"},
    {"title": "Go to the gym - Day 80", "description": "Workout for 80 minutes"},
    {"title": "Go to the gym - Day 81", "description": "Workout for 81 minutes"},
    {"title": "Go to the gym - Day 82", "description": "Workout for 82 minutes"},
    {"title": "Go to the gym - Day 83", "description": "Workout for 83 minutes"},
    {"title": "Go to the gym - Day 84", "description": "Workout for 84 minutes"},
    {"title": "Go to the gym - Day 85", "description": "Workout for 85 minutes"},
    {"title": "Go to the gym - Day 86", "description": "Workout for 86 minutes"},
    {"title": "Go to the gym - Day 87", "description": "Workout for 87 minutes"},
    {"title": "Go to the gym - Day 88", "description": "Workout for 88 minutes"},
    {"title": "Go to the gym - Day 89", "description": "Workout for 89 minutes"},
    {"title": "Go to the gym - Day 90", "description": "Workout for 90 minutes"},
    {"title": "Go to the gym - Day 91", "description": "Workout for 91 minutes"},
    {"title": "Go to the gym - Day 92", "description": "Workout for 92 minutes"},
    {"title": "Go to the gym - Day 93", "description": "Workout for 93 minutes"},
    {"title": "Go to the gym - Day 94", "description": "Workout for 94 minutes"},
    {"title": "Go to the gym - Day 95", "description": "Workout for 95 minutes"},
    {"title": "Go to the gym - Day 96", "description": "Workout for 96 minutes"},
    {"title": "Go to the gym - Day 97", "description": "Workout for 97 minutes"},
    {"title": "Go to the gym - Day 98", "description": "Workout for 98 minutes"},
    {"title": "Go to the gym - Day 99", "description": "Workout for 99 minutes"},
    {"title": "Go to the gym - Day 100", "description": "Workout for 100 minutes"},
]

BASE_URL = "http://host.docker.internal:8000/api"


class TodoAPIUser(FastHttpUser):
    @task
    def new_todos_load(self):
        with self.rest(
            "POST", f"{BASE_URL}/new_todo", json=random.choice(TODO_LSIT)
        ) as resp:
            if resp.js is None:
                pass
