version: '3'

services:
  db:
    environment:
      POSTGRES_USER: "mysecretuser"
      POSTGRES_DB: "todos"
      POSTGRES_PASSWORD: "mysecretpassword"
    image: postgres:15-alpine
    ports:
      - "5432:5432"
  web:
    restart: on-failure
    depends_on:
      - db
    build: .
    environment:
      - DATABASE_URL=postgres://mysecretuser:mysecretpassword@db:5432/todos
    ports:
      - "8000:8000"
