name: Stress Test API
author: Ruben
version: 1
architecture: linux
description: Test if we can test the API and measure it
networks:
  todo-network:
services:
  db-container:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mysecretuser
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - todo-network
    ports: 
      - 5432:5432
    volumes:
      - ./todo-api-rust/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  web:
    restart: on-failure
    depends_on:
      - db
    build: ./todo-api-rust
    environment:
      DATABASE_URL: postgres://mysecretuser:mysecretpassword@db:5432/todos
    ports:
      - 8000:8000
    networks:
      - todo-network

  test-container:
    build:
      context: ./locust
      dockerfile: Dockerfile_locust
    networks:
      - todo-network

flow:
  - name: API-Test 5 Users
    container: test-container
    commands:
      - type: console
        command: locust -u 5 -f /home/locust/locustfile.py
        note: Starting locust test
        read-notes-stdout: true

  - name: API-Test 10 Users
    container: test-container
    commands:
      - type: console
        command: locust -u 10 -f /home/locust/locustfile.py
        note: Starting locust test
        read-notes-stdout: true

  - name: API-Test 20 Users
    container: test-container
    commands:
      - type: console
        command: locust -u 20 -f /home/locust/locustfile.py 
        note: Starting locust test
        read-notes-stdout: true

  - name: API-Test 50 Users
    container: test-container
    commands:
      - type: console
        command: locust -u 50 -f /home/locust/locustfile.py 
        note: Starting locust test
        read-notes-stdout: true