name: Stress Test API
author: Ruben
version: 1
architecture: macos
description: Test if we can test the API and measure it
networks:
  todo-network:

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mysecretuser
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - todo-network
    ports:
      - 5432:5432

  web:
    restart: on-failure
    depends_on:
      - db-container
    build: ./todo-api-python
    environment:
      DATABASE_URL: postgres://mysecretuser:mysecretpassword@db:5432/todos
    ports:
      - 8000:8000
    networks:
      - todo-network

  test-container:
    image: locustio/locust
    networks:
      - todo-network
    volumes:
      - ./locust/locust.conf:/home/locust/locust.conf:ro
      - ./locust/locustfile.py:/home/locust/locustfile.py:ro

flow:
  - name: Do API-Test
    container: test-container
    commands:
      - type: console
        command: locust -f /home/locust/locustfile.py
        note: Starting locust test
        read-notes-stdout: true
