networks:
  example-network:
services:
  db-container:
    image: postgres:15:alpine
    environment:
      - POSTGRES_USER: "mysecretuser"
      - POSTGRES_DB: "todos"
      - POSTGRES_PASSWORD: "mysecretpassword"
    networks:
      - example-network
    ports: 5432:5432
  web:
    restart: on-failure
    depends_on:
      - db
    build: .
    environment:
      - DATABASE_URL=postgres://mysecretuser:mysecretpassword@db:5432/todos
    ports:
      - "8000:8000"
    networks:
      - example-network

  test-container:
    image: greencoding/puppeteer-chrome
    setup-commands:
      - cp /tmp/repo/puppeteer-flow.js /var/www/puppeteer-flow.js
    networks:
      - example-network

flow:
  - name: Check Website
    container: test-container
    commands:
      - type: console
        command: node /var/www/puppeteer-flow.js
        note: Starting Puppeteer Flow
        read-notes-stdout: true
      - type: console
        command: sleep 30
        note: Idling
      - type: console
        command: node /var/www/puppeteer-flow.js
        note: Starting Puppeteer Flow again
        read-notes-stdout: true