networks:
  todo-network:

services:
  db-container:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mysecretuser
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - todo-network
    ports:
      - 5432:5432

  web:
    restart: on-failure
    depends_on:
      - db-container
    build: .
    environment:
      DATABASE_URL: postgres://mysecretuser:mysecretpassword@db-container:5432/todos
    ports:
      - 8000:8000
    networks:
      - todo-network